### ISSUE TITLE
Add Vitanium Cloud to list of connection profiles

### ISSUE THREAD

**Issue by paulhouselander** [iterate-ch/docs#139]
Hi

We have a few customers using CyberDuck with our Object Storage so to ease set up would be very grateful if our connection profile could be added + also if we could be included in your 3rd party list? https://docs.cyberduck.io/protocols/s3/#third-party-providers

Our connection profile can be found here https://vitanium.com/app/uploads/2022/01/S3-Vitanium.zip

And a how to here https://vitanium.com/using-vitaniums-object-storage-with-cyberduck/

**Comment by AliveDevil** [comment]
Do you have any objections regarding change of filename and vendor (iterate-ch/cyberduck#12831)?

Vendor should be non-whitespace, all lowercase description of a connection, so that it can be used as URL (`s3-vitanium:/bucket`). Your profile looked more like `s3-S3 Vitanium:/bucket`, which is an invalid URL. It worked for Cyberduck, but wouldn't have worked for [Cyberduck CLI](https://duck.sh).

Check our [DigitalOcean-profile](https://github.com/iterate-ch/cyberduck/blob/master/profiles/DigitalOcean%20Spaces%20(fra1).cyberduckprofile), which is comparable to yours for the future.

**Comment by paulhouselander** [comment]
Thanks appreciate the response, no problem at all, apologies we did not realise the Vendor should be non-whitespace.
[vitanium-logomark]
Paul Houselander
Technical Director

***@***.******@***.***>
0345 258 1500

View our disclaimer<https://vitanium.com/email-disclaimer/>

**Comment by dkocher** [comment]
With iterate-ch/cyberduck#12831 this is now live.

![Screenshot 2022-01-27 at 14 18 31](https://user-images.githubusercontent.com/71733/151366805-22ab1b99-95ff-4970-9ed1-9e8ad952d75f.png)
