### ISSUE TITLE
Document file length limitation with Cryptomator

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/docs#300]
Document the hard-cap of 146 bytes plaintext filenames.

Length limit in bytes: All single-byte encodings of characters can use the total amount of bytes available. Multibyte-encodings of files (diacritics, glyphs, etc.) may shorten the observed file name length.

**Comment by jkscx** [comment]
Hello, I think I'm hitting this limit. Namely, when I try to create (or rename) a file to a filename longer than 146 ascii chars (146 bytes) inside an Crytpomator vault I get the following error:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/18429283/227782261-f7c5643f-618b-46c2-b1d0-d8869d7dfa3b.png">

Although, in my case, it's while in Online-mode and not in Smart Sync-mode. (Maybe it kept the limit of the Smart Sync-mode because previously the drive was in that mode before I changed it to Online-mode?)

As the issue sounds like this and because the error message isn't helpful at all (even deceptive if it's a file length limit), I wanted to ask if my issue is in fact caused by the file length limit of Mountain Duck?

Hope you can help.

**Comment by AliveDevil** [comment]
Looks like you're hitting that issue, yes. The filename length limit is _exactly_ 146 characters - any longer and that will cause issues (file extension ".txt", ".docx", etc. included).

Interestingly this does happen in the Online mode for me as well with the 146 character limit. Best workaround at the moment is keeping shorter file names.
